//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficerStatus.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="officerInfo", Namespace="SecureWebService")]
    [System.SerializableAttribute()]
    public partial class officerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublickeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string officerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publickey {
            get {
                return this.PublickeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PublickeyField, value) != true)) {
                    this.PublickeyField = value;
                    this.RaisePropertyChanged("Publickey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string officerId {
            get {
                return this.officerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.officerIdField, value) != true)) {
                    this.officerIdField = value;
                    this.RaisePropertyChanged("officerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SecureWebService", ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="SecureWebService/IService1/GetPublicKey", ReplyAction="SecureWebService/IService1/GetPublicKeyResponse")]
        string GetPublicKey();
        
        [System.ServiceModel.OperationContractAttribute(Action="SecureWebService/IService1/GetPublicKey", ReplyAction="SecureWebService/IService1/GetPublicKeyResponse")]
        System.Threading.Tasks.Task<string> GetPublicKeyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="SecureWebService/IService1/SetStatus", ReplyAction="SecureWebService/IService1/SetStatusResponse")]
        bool SetStatus(OfficerStatus.ServiceReference1.officerInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="SecureWebService/IService1/SetStatus", ReplyAction="SecureWebService/IService1/SetStatusResponse")]
        System.Threading.Tasks.Task<bool> SetStatusAsync(OfficerStatus.ServiceReference1.officerInfo info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : OfficerStatus.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<OfficerStatus.ServiceReference1.IService1>, OfficerStatus.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPublicKey() {
            return base.Channel.GetPublicKey();
        }
        
        public System.Threading.Tasks.Task<string> GetPublicKeyAsync() {
            return base.Channel.GetPublicKeyAsync();
        }
        
        public bool SetStatus(OfficerStatus.ServiceReference1.officerInfo info) {
            return base.Channel.SetStatus(info);
        }
        
        public System.Threading.Tasks.Task<bool> SetStatusAsync(OfficerStatus.ServiceReference1.officerInfo info) {
            return base.Channel.SetStatusAsync(info);
        }
    }
}
